### ISSUE TITLE
[Bug] mod straight up doesnt work (Fabric 1.20.1)

### ISSUE THREAD

**Issue by memphismc** [MastroCaleb/OverEnchanted#1]
https://github.com/MastroCaleb/OverEnchanted/assets/129392333/57f373de-1453-4b08-a1eb-a1b29014cf24

in 1.19.2 it was working just fine with basically the same modpack

**Comment by MastroCaleb** [comment]
i think this might be a compatibility issue with other mods. the mod works fine alone but it has shown various problems with other mods that change how the anvil works. i haven't updated the mod in a while but im going to change how it works fundamentally to allow compatibility.

**Comment by memphismc** [comment]
> i think this might be a compatibility issue with other mods. the mod works fine alone but it has shown various problems with other mods that change how the anvil works. i haven't updated the mod in a while but im going to change how it works fundamentally to allow compatibility.
> 
> i will close this issue once the mod is updated.

i remember in 1.19.2 when we talked about adventurez being a problem making the game crash on launch, but here i tested and the game runs but overenchanted doesnt work with or without adventurez

**Comment by MastroCaleb** [comment]
> i remember in 1.19.2 when we talked about adventurez being a problem making the game crash on launch, but here i tested and the game runs but overenchanted doesnt work with or without adventurez

could be any other mod, adventurez made mc crash, maybe this mod fundamentally changes the anvil class so my mod simply ignores the implementation and doesnt work. there are smoother and better methods to make Overnenchanted, the one i had used is a bit too complicated and really shouldn't be used at all as it is instable. im sorry for any inconvenience

**Comment by memphismc** [comment]
> > i remember in 1.19.2 when we talked about adventurez being a problem making the game crash on launch, but here i tested and the game runs but overenchanted doesnt work with or without adventurez
> 
> could be any other mod, adventurez made mc crash, maybe this mod fundamentally changes the anvil class so my mod simply ignores the implementation and doesnt work. there are smoother and better methods to make Overnenchanted, the one i had used is a bit too complicated and really shouldn't be used at all as it is unstable. im sorry for any inconvenience.
> 
> This fix should also make OverEnchanted work with adventurez

great, just out of curiosity not impatience, when is the fix coming? or when are you gonna work on it might be a better question

**Comment by MastroCaleb** [comment]
> > > i remember in 1.19.2 when we talked about adventurez being a problem making the game crash on launch, but here i tested and the game runs but overenchanted doesnt work with or without adventurez
> > 
> > 
> > could be any other mod, adventurez made mc crash, maybe this mod fundamentally changes the anvil class so my mod simply ignores the implementation and doesnt work. there are smoother and better methods to make Overnenchanted, the one i had used is a bit too complicated and really shouldn't be used at all as it is unstable. im sorry for any inconvenience.
> > This fix should also make OverEnchanted work with adventurez
> 
> great, just out of curiosity not impatience, when is the fix coming? or when are you gonna work on it might be a better question

As this is an actual issue and the mod is not working properly i already started looking for a fix, i'll keep working on it tomorrow and it should be ready by then. Keeping tomorrow as a deadline so i actually commit to this.

If i don't update this by tomorrow you are free to spam me here, i get an email everytime you reply so im forced to see it, i unfortunately have some procastination issues lol

**Comment by MastroCaleb** [comment]
> > > i remember in 1.19.2 when we talked about adventurez being a problem making the game crash on launch, but here i tested and the game runs but overenchanted doesnt work with or without adventurez
> > 
> > 
> > could be any other mod, adventurez made mc crash, maybe this mod fundamentally changes the anvil class so my mod simply ignores the implementation and doesnt work. there are smoother and better methods to make Overnenchanted, the one i had used is a bit too complicated and really shouldn't be used at all as it is unstable. im sorry for any inconvenience.
> > This fix should also make OverEnchanted work with adventurez
> 
> great, just out of curiosity not impatience, when is the fix coming? or when are you gonna work on it might be a better question

Hello, i have just uploaded the update that should fix this. CurseForge hasn't yet accepted the files but once it will you will be able to download the new version.

Please if any error/bug/crash appears, let me know. (Also be careful and download the FABRIC version as i also updated the forge one)

**Comment by MastroCaleb** [comment]
> > > > i remember in 1.19.2 when we talked about adventurez being a problem making the game crash on launch, but here i tested and the game runs but overenchanted doesnt work with or without adventurez
> > > 
> > > 
> > > could be any other mod, adventurez made mc crash, maybe this mod fundamentally changes the anvil class so my mod simply ignores the implementation and doesnt work. there are smoother and better methods to make Overnenchanted, the one i had used is a bit too complicated and really shouldn't be used at all as it is unstable. im sorry for any inconvenience.
> > > This fix should also make OverEnchanted work with adventurez
> > 
> > 
> > great, just out of curiosity not impatience, when is the fix coming? or when are you gonna work on it might be a better question
> 
> Hello, i have just uploaded the update that should fix this. CurseForge hasn't yet accepted the files but once it will you will be able to download the new version.
> 
> Please if any error/bug/crash appears, let me know. (Also be careful and download the FABRIC version as i also updated the forge one)

The version is up and can now be downloaded!

**Comment by memphismc** [comment]
> > > > > i remember in 1.19.2 when we talked about adventurez being a problem making the game crash on launch, but here i tested and the game runs but overenchanted doesnt work with or without adventurez
> > > > 
> > > > 
> > > > could be any other mod, adventurez made mc crash, maybe this mod fundamentally changes the anvil class so my mod simply ignores the implementation and doesnt work. there are smoother and better methods to make Overnenchanted, the one i had used is a bit too complicated and really shouldn't be used at all as it is unstable. im sorry for any inconvenience.
> > > > This fix should also make OverEnchanted work with adventurez
> > > 
> > > 
> > > great, just out of curiosity not impatience, when is the fix coming? or when are you gonna work on it might be a better question
> > 
> > 
> > Hello, i have just uploaded the update that should fix this. CurseForge hasn't yet accepted the files but once it will you will be able to download the new version.
> > Please if any error/bug/crash appears, let me know. (Also be careful and download the FABRIC version as i also updated the forge one)
> 
> The version is up and can now be downloaded!

damn, still doesnt work :(

**Comment by memphismc** [comment]
> > > > > > > i remember in 1.19.2 when we talked about adventurez being a problem making the game crash on launch, but here i tested and the game runs but overenchanted doesnt work with or without adventurez
> > > > > > 
> > > > > > 
> > > > > > could be any other mod, adventurez made mc crash, maybe this mod fundamentally changes the anvil class so my mod simply ignores the implementation and doesnt work. there are smoother and better methods to make Overnenchanted, the one i had used is a bit too complicated and really shouldn't be used at all as it is unstable. im sorry for any inconvenience.
> > > > > > This fix should also make OverEnchanted work with adventurez
> > > > > 
> > > > > 
> > > > > great, just out of curiosity not impatience, when is the fix coming? or when are you gonna work on it might be a better question
> > > > 
> > > > 
> > > > Hello, i have just uploaded the update that should fix this. CurseForge hasn't yet accepted the files but once it will you will be able to download the new version.
> > > > Please if any error/bug/crash appears, let me know. (Also be careful and download the FABRIC version as i also updated the forge one)
> > > 
> > > 
> > > The version is up and can now be downloaded!
> > 
> > 
> > damn, still doesnt work :(
> 
> does it crash or does it just not work? and if it just does not work may i ask if you have installed the mod "Easy Anvils"?

game runs, but enchantments just dont go above their limit
had easy anvils a while ago but uninstalled due to some weird duping bug, i do have easy magic installed if that makes any difference tho

**Comment by MastroCaleb** [comment]
> > > > > > > > i remember in 1.19.2 when we talked about adventurez being a problem making the game crash on launch, but here i tested and the game runs but overenchanted doesnt work with or without adventurez
> > > > > > > 
> > > > > > > 
> > > > > > > could be any other mod, adventurez made mc crash, maybe this mod fundamentally changes the anvil class so my mod simply ignores the implementation and doesnt work. there are smoother and better methods to make Overnenchanted, the one i had used is a bit too complicated and really shouldn't be used at all as it is unstable. im sorry for any inconvenience.
> > > > > > > This fix should also make OverEnchanted work with adventurez
> > > > > > 
> > > > > > 
> > > > > > great, just out of curiosity not impatience, when is the fix coming? or when are you gonna work on it might be a better question
> > > > > 
> > > > > 
> > > > > Hello, i have just uploaded the update that should fix this. CurseForge hasn't yet accepted the files but once it will you will be able to download the new version.
> > > > > Please if any error/bug/crash appears, let me know. (Also be careful and download the FABRIC version as i also updated the forge one)
> > > > 
> > > > 
> > > > The version is up and can now be downloaded!
> > > 
> > > 
> > > damn, still doesnt work :(
> > 
> > 
> > does it crash or does it just not work? and if it just does not work may i ask if you have installed the mod "Easy Anvils"?
> 
> game runs, but enchantments just dont go above their limit had easy anvils a while ago but uninstalled due to some weird duping bug, i do have easy magic installed if that makes any difference tho

nope that mod should be ok. i don't really know what is causing this. is it a publicly available modpack or did you make it yourself? in case, would you be able to send me the rar/zip file with every mod so that i can try and troubleshoot the issue?

**Comment by memphismc** [comment]
> > > > > > > > > i remember in 1.19.2 when we talked about adventurez being a problem making the game crash on launch, but here i tested and the game runs but overenchanted doesnt work with or without adventurez
> > > > > > > > 
> > > > > > > > 
> > > > > > > > could be any other mod, adventurez made mc crash, maybe this mod fundamentally changes the anvil class so my mod simply ignores the implementation and doesnt work. there are smoother and better methods to make Overnenchanted, the one i had used is a bit too complicated and really shouldn't be used at all as it is unstable. im sorry for any inconvenience.
> > > > > > > > This fix should also make OverEnchanted work with adventurez
> > > > > > > 
> > > > > > > 
> > > > > > > great, just out of curiosity not impatience, when is the fix coming? or when are you gonna work on it might be a better question
> > > > > > 
> > > > > > 
> > > > > > Hello, i have just uploaded the update that should fix this. CurseForge hasn't yet accepted the files but once it will you will be able to download the new version.
> > > > > > Please if any error/bug/crash appears, let me know. (Also be careful and download the FABRIC version as i also updated the forge one)
> > > > > 
> > > > > 
> > > > > The version is up and can now be downloaded!
> > > > 
> > > > 
> > > > damn, still doesnt work :(
> > > 
> > > 
> > > does it crash or does it just not work? and if it just does not work may i ask if you have installed the mod "Easy Anvils"?
> > 
> > 
> > game runs, but enchantments just dont go above their limit had easy anvils a while ago but uninstalled due to some weird duping bug, i do have easy magic installed if that makes any difference tho
> 
> nope that mod should be ok. i don't really know what is causing this. is it a publicly available modpack or did you make it yourself? in case, would you be able to send me the rar/zip file with every mod so that i can try and troubleshoot the issue?

ive definitely done some tests myself but not fully since its quite a lot of mods, but again, this same modpack worked fine in 1.19.2, i'll send in a second

**Comment by memphismc** [comment]
https://drive.google.com/file/d/1xsrF2Y7_kfZNcVM6-1-KAS1VSV10Qm6e/view?usp=sharing

i made it, kind of vanilla+ with my own twist on it, rpg, lots of structures, main mods being player ex, relic ex (player leveling) improved mobs (mob scaling), mythic metals, betternether, betterend, soulslike weaponry (mostly cause of its compats with simplyswords/knaves needs)

these probably dont concern you, while mythic metals, betternether, betterend, soulslike weaponry do add their own enchantments and anvils in 1.19.2 they didnt affect overenchanted's functionality at all (though i havent tested it here)

spellbound, extra damage enchantments, combat enchantments, majrusz's enchantments, alessandvr's enchantments etc. (the ones i listed arent all of them i think) are mods that add enchantments but to my knowledge dont change how the anvils work/how enchantments combine (havent tested without them, though spellbound worked fine with overenc in 1.19.2, im not sure for the other enchantment addition mods since this is the first time ive used any other enchantment addition mod other than spellbound, i did use alessandvr's enchantments which worked fine but ended up removing it due to a crash it causes with one of its enchants, dont worry it has nothing to do with overenc)

i should mention that ive had overenchanted since the very start of this modpack and i havent really tested to see if it works until yesterday when i tried combining an enchantment which didnt go above its limit, so who knows how long this issue has been going for cause with time ive added new mods

i can also give you my config files, though i dont think you need them but if you do just lmk

**Comment by MastroCaleb** [comment]
> https://drive.google.com/file/d/1xsrF2Y7_kfZNcVM6-1-KAS1VSV10Qm6e/view?usp=sharing
> 
> i made it, kind of vanilla+ with my own twist on it, rpg, lots of structures, main mods being player ex, relic ex (player leveling) improved mobs (mob scaling), mythic metals, betternether, betterend, soulslike weaponry (mostly cause of its compats with simplyswords/knaves needs)
> 
> these probably dont concern you, while mythic metals, betternether, betterend, soulslike weaponry do add their own enchantments and anvils in 1.19.2 they didnt affect overenchanted's functionality at all (though i havent tested it here)
> 
> spellbound, extra damage enchantments, combat enchantments, majrusz's enchantments, alessandvr's enchantments etc. (the ones i listed arent all of them i think) are mods that add enchantments but to my knowledge dont change how the anvils work/how enchantments combine (havent tested without them, though spellbound worked fine with overenc in 1.19.2, im not sure for the other enchantment addition mods since this is the first time ive used any other enchantment addition mod other than spellbound, i did use alessandvr's enchantments in 1.19.2 which worked fine with overenc but ended up removing it due to a crash it causes with one of its enchants, dont worry the crash had nothing to do with overenc)
> 
> i should mention that ive had overenchanted since the very start of this modpack and i havent really tested to see if it works until yesterday when i tried combining an enchantment which didnt go above its limit, so who knows how long this issue has been going for cause with time ive added new mods
> 
> i can also give you my config files, though i dont think you need them but if you do just lmk

Thanks you! I will try once i have a little more of a free schedule (hard week in school). Im intrigued by this problem because usually the mod if it doesn't work it should just crash, but somehow here it just does not work.

Im keeping this issue open until i have a working version. Thanks for the report! :)

**Comment by memphismc** [comment]
> > https://drive.google.com/file/d/1xsrF2Y7_kfZNcVM6-1-KAS1VSV10Qm6e/view?usp=sharing
> > i made it, kind of vanilla+ with my own twist on it, rpg, lots of structures, main mods being player ex, relic ex (player leveling) improved mobs (mob scaling), mythic metals, betternether, betterend, soulslike weaponry (mostly cause of its compats with simplyswords/knaves needs)
> > these probably dont concern you, while mythic metals, betternether, betterend, soulslike weaponry do add their own enchantments and anvils in 1.19.2 they didnt affect overenchanted's functionality at all (though i havent tested it here)
> > spellbound, extra damage enchantments, combat enchantments, majrusz's enchantments, alessandvr's enchantments etc. (the ones i listed arent all of them i think) are mods that add enchantments but to my knowledge dont change how the anvils work/how enchantments combine (havent tested without them, though spellbound worked fine with overenc in 1.19.2, im not sure for the other enchantment addition mods since this is the first time ive used any other enchantment addition mod other than spellbound, i did use alessandvr's enchantments in 1.19.2 which worked fine with overenc but ended up removing it due to a crash it causes with one of its enchants, dont worry the crash had nothing to do with overenc)
> > i should mention that ive had overenchanted since the very start of this modpack and i havent really tested to see if it works until yesterday when i tried combining an enchantment which didnt go above its limit, so who knows how long this issue has been going for cause with time ive added new mods
> > i can also give you my config files, though i dont think you need them but if you do just lmk
> 
> Thank you! I will try once i have a little more of a free schedule (harsh week in school). Im intrigued by this problem because usually the mod if it doesn't work it should just crash, but somehow here it just does not work.
> 
> Im keeping this issue open until i have a working version. Thanks for the report! :)

thank you so much for your god given patience to be able to do this with 300 mods, i couldnt even with all the free time in the world :))))
please do let me know which mod is it that fucks up how the anvil works modded-wise, since it also messes up a relicex  mechanic (a mod that adds relics, a relic is an armor piece, currently only chestplate and helmet versions are available, that have random rpg stats such as +25% attack speed, +1 hp regen etc. which can be affixed to normal armor but the end result is this.....)


https://github.com/MastroCaleb/OverEnchanted/assets/129392333/57f9a983-34ed-4fcb-861c-43094c993917



relicex devs said it doesnt happen on its own so its definitely some mod messing up the anvils

**Comment by MastroCaleb** [comment]
> relicex devs said it doesnt happen on its own so its definitely some mod messing up the anvils

no problem! it's absolutely another mod that has completely fucked up the anvil (can't blame them honestly mixins are hard to use) also for me it will be a bit easier to understand why my mod doesn't work as i can simply make a debugger version that writes some messages in the log when it tries to OverEnchant something. There are 2 cases: the message writes correctly (huge problem on my hand, could be my fault), or the message does not (i can't do anything about it and will try to identify which mod changes the anvil's behaviour)

**Comment by memphismc** [comment]
> > relicex devs said it doesnt happen on its own so its definitely some mod messing up the anvils
> 
> no problem! it's absolutely another mod that has completely fucked up the anvil (can't blame them honestly mixins are hard to use) also for me it will be a bit easier to understand why my mod doesn't work as i can simply make a debugger version that writes some messages in the log when it tries to OverEnchant something. There are 2 cases: the message writes correctly (huge problem on my hand, could be my fault), or the message does not (i can't do anything about it and will try to identify which mod changes the anvil's behaviour)

i have tried removing mods that have to do with anvils and enchantments, surprisingly theyre not the issue

so at this point im completely lost

**Comment by memphismc** [comment]
> > > > relicex devs said it doesnt happen on its own so its definitely some mod messing up the anvils
> > > 
> > > 
> > > no problem! it's absolutely another mod that has completely fucked up the anvil (can't blame them honestly mixins are hard to use) also for me it will be a bit easier to understand why my mod doesn't work as i can simply make a debugger version that writes some messages in the log when it tries to OverEnchant something. There are 2 cases: the message writes correctly (huge problem on my hand, could be my fault), or the message does not (i can't do anything about it and will try to identify which mod changes the anvil's behaviour)
> > 
> > 
> > i have tried removing mods that have to do with anvils and enchantments, surprisingly theyre not the issue
> > so at this point im completely lost
> 
> im just going to do this:
> 
> * Add overenchanted in the mod folder
> * Add 10-20 mods of the modpack
> * Check if overenchanted works or not
> * It works? Add 10-20 other mods
> * Doesn't work? Remove 5-10 mods of the 10-20 i just added and check if it works, repeat.
> * Eventually find which mod conflicts
> 
> I also do this while making modpacks and a mod crashes the game

binary searches are the most tedious things ever, issues such as these honestly ruin my experience with modded minecraft
best of luck to you in this search, thanks a ton in advance

**Comment by MastroCaleb** [comment]
> > > > > relicex devs said it doesnt happen on its own so its definitely some mod messing up the anvils
> > > > 
> > > > 
> > > > no problem! it's absolutely another mod that has completely fucked up the anvil (can't blame them honestly mixins are hard to use) also for me it will be a bit easier to understand why my mod doesn't work as i can simply make a debugger version that writes some messages in the log when it tries to OverEnchant something. There are 2 cases: the message writes correctly (huge problem on my hand, could be my fault), or the message does not (i can't do anything about it and will try to identify which mod changes the anvil's behaviour)
> > > 
> > > 
> > > i have tried removing mods that have to do with anvils and enchantments, surprisingly theyre not the issue
> > > so at this point im completely lost
> > 
> > 
> > im just going to do this:
> > 
> > * Add overenchanted in the mod folder
> > * Add 10-20 mods of the modpack
> > * Check if overenchanted works or not
> > * It works? Add 10-20 other mods
> > * Doesn't work? Remove 5-10 mods of the 10-20 i just added and check if it works, repeat.
> > * Eventually find which mod conflicts
> > 
> > I also do this while making modpacks and a mod crashes the game
> 
> binary searches are the most tedious things ever, issues such as these honestly ruin my experience with modded minecraft best of luck to you in this search, thanks a ton in advance

i completely understand. i somehow and for some reason actually like troubleshooting lol

**Comment by memphismc** [comment]
> > > > > > relicex devs said it doesnt happen on its own so its definitely some mod messing up the anvils
> > > > > 
> > > > > 
> > > > > no problem! it's absolutely another mod that has completely fucked up the anvil (can't blame them honestly mixins are hard to use) also for me it will be a bit easier to understand why my mod doesn't work as i can simply make a debugger version that writes some messages in the log when it tries to OverEnchant something. There are 2 cases: the message writes correctly (huge problem on my hand, could be my fault), or the message does not (i can't do anything about it and will try to identify which mod changes the anvil's behaviour)
> > > > 
> > > > 
> > > > i have tried removing mods that have to do with anvils and enchantments, surprisingly theyre not the issue
> > > > so at this point im completely lost
> > > 
> > > 
> > > im just going to do this:
> > > 
> > > * Add overenchanted in the mod folder
> > > * Add 10-20 mods of the modpack
> > > * Check if overenchanted works or not
> > > * It works? Add 10-20 other mods
> > > * Doesn't work? Remove 5-10 mods of the 10-20 i just added and check if it works, repeat.
> > > * Eventually find which mod conflicts
> > > 
> > > I also do this while making modpacks and a mod crashes the game
> > 
> > 
> > binary searches are the most tedious things ever, issues such as these honestly ruin my experience with modded minecraft best of luck to you in this search, thanks a ton in advance
> 
> i completely understand. i somehow and for some reason actually like troubleshooting lol

![image](https://github.com/MastroCaleb/OverEnchanted/assets/129392333/27f958b1-0563-4265-820a-9a72b823c9d8)

i should mention, the anvil has these weird arrows that dont really do anything, which only show if you have no items at all in your inventory, if you have an item, anything, even an item that unusable in the anvil those arrows dissapear, strange

**Comment by MastroCaleb** [comment]
> > > > > > > relicex devs said it doesnt happen on its own so its definitely some mod messing up the anvils
> > > > > > 
> > > > > > 
> > > > > > no problem! it's absolutely another mod that has completely fucked up the anvil (can't blame them honestly mixins are hard to use) also for me it will be a bit easier to understand why my mod doesn't work as i can simply make a debugger version that writes some messages in the log when it tries to OverEnchant something. There are 2 cases: the message writes correctly (huge problem on my hand, could be my fault), or the message does not (i can't do anything about it and will try to identify which mod changes the anvil's behaviour)
> > > > > 
> > > > > 
> > > > > i have tried removing mods that have to do with anvils and enchantments, surprisingly theyre not the issue
> > > > > so at this point im completely lost
> > > > 
> > > > 
> > > > im just going to do this:
> > > > 
> > > > * Add overenchanted in the mod folder
> > > > * Add 10-20 mods of the modpack
> > > > * Check if overenchanted works or not
> > > > * It works? Add 10-20 other mods
> > > > * Doesn't work? Remove 5-10 mods of the 10-20 i just added and check if it works, repeat.
> > > > * Eventually find which mod conflicts
> > > > 
> > > > I also do this while making modpacks and a mod crashes the game
> > > 
> > > 
> > > binary searches are the most tedious things ever, issues such as these honestly ruin my experience with modded minecraft best of luck to you in this search, thanks a ton in advance
> > 
> > 
> > i completely understand. i somehow and for some reason actually like troubleshooting lol
> 
> ![image](https://private-user-images.githubusercontent.com/129392333/310295573-27f958b1-0563-4265-820a-9a72b823c9d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzczMjYsIm5iZiI6MTcwOTY3NzAyNiwicGF0aCI6Ii8xMjkzOTIzMzMvMzEwMjk1NTczLTI3Zjk1OGIxLTA1NjMtNDI2NS04MjBhLTlhNzJiODIzYzlkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQyMjE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTAzMzYxMmViZDZkNzViYjY0NGFhNmU1NGI1NTVkZTc1NzEyZGFhM2M5MWFjMjI4ZDU4MGI4ZWI3ODg5NTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pzobBuAKwRpNs6b5Va6ep5cwLCWyK2oyqpWbtyLF5Fk)
> 
> i should mention, the anvil has these weird arrows that dont really do anything, which only show if you have no items at all in your inventory, if you have an item, anything, even an item that unusable in the anvil those arrows dissapear, strange

weird, do you know which mod adds these?

**Comment by memphismc** [comment]
> > > > > > > > relicex devs said it doesnt happen on its own so its definitely some mod messing up the anvils
> > > > > > > 
> > > > > > > 
> > > > > > > no problem! it's absolutely another mod that has completely fucked up the anvil (can't blame them honestly mixins are hard to use) also for me it will be a bit easier to understand why my mod doesn't work as i can simply make a debugger version that writes some messages in the log when it tries to OverEnchant something. There are 2 cases: the message writes correctly (huge problem on my hand, could be my fault), or the message does not (i can't do anything about it and will try to identify which mod changes the anvil's behaviour)
> > > > > > 
> > > > > > 
> > > > > > i have tried removing mods that have to do with anvils and enchantments, surprisingly theyre not the issue
> > > > > > so at this point im completely lost
> > > > > 
> > > > > 
> > > > > im just going to do this:
> > > > > 
> > > > > * Add overenchanted in the mod folder
> > > > > * Add 10-20 mods of the modpack
> > > > > * Check if overenchanted works or not
> > > > > * It works? Add 10-20 other mods
> > > > > * Doesn't work? Remove 5-10 mods of the 10-20 i just added and check if it works, repeat.
> > > > > * Eventually find which mod conflicts
> > > > > 
> > > > > I also do this while making modpacks and a mod crashes the game
> > > > 
> > > > 
> > > > binary searches are the most tedious things ever, issues such as these honestly ruin my experience with modded minecraft best of luck to you in this search, thanks a ton in advance
> > > 
> > > 
> > > i completely understand. i somehow and for some reason actually like troubleshooting lol
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/129392333/310295573-27f958b1-0563-4265-820a-9a72b823c9d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzczMjYsIm5iZiI6MTcwOTY3NzAyNiwicGF0aCI6Ii8xMjkzOTIzMzMvMzEwMjk1NTczLTI3Zjk1OGIxLTA1NjMtNDI2NS04MjBhLTlhNzJiODIzYzlkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQyMjE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTAzMzYxMmViZDZkNzViYjY0NGFhNmU1NGI1NTVkZTc1NzEyZGFhM2M5MWFjMjI4ZDU4MGI4ZWI3ODg5NTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pzobBuAKwRpNs6b5Va6ep5cwLCWyK2oyqpWbtyLF5Fk)
> > i should mention, the anvil has these weird arrows that dont really do anything, which only show if you have no items at all in your inventory, if you have an item, anything, even an item that unusable in the anvil those arrows dissapear, strange
> 
> weird, do you know which mod adds these?

no idea, im willing to bet its the mod thats causing all this trouble though

**Comment by MastroCaleb** [comment]
> > > > > > > > > relicex devs said it doesnt happen on its own so its definitely some mod messing up the anvils
> > > > > > > > 
> > > > > > > > 
> > > > > > > > no problem! it's absolutely another mod that has completely fucked up the anvil (can't blame them honestly mixins are hard to use) also for me it will be a bit easier to understand why my mod doesn't work as i can simply make a debugger version that writes some messages in the log when it tries to OverEnchant something. There are 2 cases: the message writes correctly (huge problem on my hand, could be my fault), or the message does not (i can't do anything about it and will try to identify which mod changes the anvil's behaviour)
> > > > > > > 
> > > > > > > 
> > > > > > > i have tried removing mods that have to do with anvils and enchantments, surprisingly theyre not the issue
> > > > > > > so at this point im completely lost
> > > > > > 
> > > > > > 
> > > > > > im just going to do this:
> > > > > > 
> > > > > > * Add overenchanted in the mod folder
> > > > > > * Add 10-20 mods of the modpack
> > > > > > * Check if overenchanted works or not
> > > > > > * It works? Add 10-20 other mods
> > > > > > * Doesn't work? Remove 5-10 mods of the 10-20 i just added and check if it works, repeat.
> > > > > > * Eventually find which mod conflicts
> > > > > > 
> > > > > > I also do this while making modpacks and a mod crashes the game
> > > > > 
> > > > > 
> > > > > binary searches are the most tedious things ever, issues such as these honestly ruin my experience with modded minecraft best of luck to you in this search, thanks a ton in advance
> > > > 
> > > > 
> > > > i completely understand. i somehow and for some reason actually like troubleshooting lol
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/129392333/310295573-27f958b1-0563-4265-820a-9a72b823c9d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzczMjYsIm5iZiI6MTcwOTY3NzAyNiwicGF0aCI6Ii8xMjkzOTIzMzMvMzEwMjk1NTczLTI3Zjk1OGIxLTA1NjMtNDI2NS04MjBhLTlhNzJiODIzYzlkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQyMjE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTAzMzYxMmViZDZkNzViYjY0NGFhNmU1NGI1NTVkZTc1NzEyZGFhM2M5MWFjMjI4ZDU4MGI4ZWI3ODg5NTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pzobBuAKwRpNs6b5Va6ep5cwLCWyK2oyqpWbtyLF5Fk)
> > > i should mention, the anvil has these weird arrows that dont really do anything, which only show if you have no items at all in your inventory, if you have an item, anything, even an item that unusable in the anvil those arrows dissapear, strange
> > 
> > 
> > weird, do you know which mod adds these?
> 
> no idea, im willing to bet its the mod thats causing all this trouble though

most probably, thanks for the info

**Comment by memphismc** [comment]
just checking in, i installed goblin trader mod to see how it is and its able to sell overenchanted gear which completely confused and surprised me the first time i saw it

![image](https://github.com/MastroCaleb/OverEnchanted/assets/129392333/3fbe5e3b-e4c8-4b92-ba0f-4b7ba1eb5524)


as for the issue at hand, i still havent found the culprit mod thats causing all this annoying bs with the anvil
have you made any progress? of course im not expecting you to find out that fast, modpack is damn near 300 mods its bound to take a while

**Comment by MastroCaleb** [comment]
> just checking in, i installed goblin trader mod to see how it is and its able to sell overenchanted gear which completely confused and surprised me the first time i saw it
> 
> ![image](https://private-user-images.githubusercontent.com/129392333/312206695-3fbe5e3b-e4c8-4b92-ba0f-4b7ba1eb5524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzA4NDUsIm5iZiI6MTcxMDI3MDU0NSwicGF0aCI6Ii8xMjkzOTIzMzMvMzEyMjA2Njk1LTNmYmU1ZTNiLWU0YzgtNGI5Mi1iYTBmLTRiN2JhMWViNTUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxOTA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDhiMWE2MmMxOTYxODE0ZGI0MGRkOWZiM2I2ZjEzNTQxZjE4NjA2ODFkYjZkZDc1YzkzMDU1MjMyY2JiMDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dgl8gngMqdt-TklSIAGcTTunGRpdXp-LozD4TWKqH80)
> 
> as for the issue at hand, i still havent found the culprit mod thats causing all this annoying bs with the anvil have you made any progress? of course im not expecting you to find out that fast, modpack is damn near 300 mods its bound to take a while

Hi, Goblin Traders have the ability to sell levels that are 1 over the vanilla max. This is not thanks to OverEnchanted, it's a goblin trader feature. I have time to test the modpack rn so expect news in a couple of hours

**Comment by memphismc** [comment]
> > just checking in, i installed goblin trader mod to see how it is and its able to sell overenchanted gear which completely confused and surprised me the first time i saw it
> > ![image](https://private-user-images.githubusercontent.com/129392333/312206695-3fbe5e3b-e4c8-4b92-ba0f-4b7ba1eb5524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzA4NDUsIm5iZiI6MTcxMDI3MDU0NSwicGF0aCI6Ii8xMjkzOTIzMzMvMzEyMjA2Njk1LTNmYmU1ZTNiLWU0YzgtNGI5Mi1iYTBmLTRiN2JhMWViNTUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxOTA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDhiMWE2MmMxOTYxODE0ZGI0MGRkOWZiM2I2ZjEzNTQxZjE4NjA2ODFkYjZkZDc1YzkzMDU1MjMyY2JiMDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dgl8gngMqdt-TklSIAGcTTunGRpdXp-LozD4TWKqH80)
> > as for the issue at hand, i still havent found the culprit mod thats causing all this annoying bs with the anvil have you made any progress? of course im not expecting you to find out that fast, modpack is damn near 300 mods its bound to take a while
> 
> Hi, Goblin Traders have the ability to sell levels that are 1 over the vanilla max. This is not thanks to OverEnchanted, it's a goblin trader feature. I have time to test the modpack rn so expect news in a couple of hours

oh dw ik thats their unique feature and overenc has nothing to do with it lol
thank you btw, take your time

**Comment by memphismc** [comment]
btw ive added a few new mods and removed a few others, all in all modpack hasnt changed much at all and this issue with the anvil is still ongoing sadly

lmk if you want the "new" modpack

**Comment by MastroCaleb** [comment]
> btw ive added a few new mods and removed a few others, all in all modpack hasnt changed much at all and this issue with the anvil is still ongoing sadly
> 
> lmk if you want the "new" modpack

currently removing TONS of mods and the issue persists, it seems that a mod changes the result of the anvil and by accident reverts the overenchantment

**Comment by memphismc** [comment]
> > btw ive added a few new mods and removed a few others, all in all modpack hasnt changed much at all and this issue with the anvil is still ongoing sadly
> > lmk if you want the "new" modpack
> 
> currently removing TONS of mods and the issue persists, it seems that a mod changes the result of the anvil and by accident reverts the overenchantment

again, you have godsent patience to be able to do this and i cant thank you enough

as for the situation at hand i really dont know what to say, could it be a mod that tweaks the anvil yet it doesnt state that it does or it did state it and it went over my head somehow??

**Comment by MastroCaleb** [comment]
> > > btw ive added a few new mods and removed a few others, all in all modpack hasnt changed much at all and this issue with the anvil is still ongoing sadly
> > > lmk if you want the "new" modpack
> > 
> > 
> > currently removing TONS of mods and the issue persists, it seems that a mod changes the result of the anvil and by accident reverts the overenchantment
> 
> again, you have godsent patience to be able to do this and i cant thank you enough
> 
> as for the situation at hand i really dont know what to say, could it be a mod that tweaks the anvil yet it doesnt state that it does or it did state it and it went over my head somehow??

yeah it absolutely is. many mods might need to modify the anvil to have one feature working, one example of this is adventurez (but i already testet with and without it :d )

**Comment by memphismc** [comment]
> > > > btw ive added a few new mods and removed a few others, all in all modpack hasnt changed much at all and this issue with the anvil is still ongoing sadly
> > > > lmk if you want the "new" modpack
> > > 
> > > 
> > > currently removing TONS of mods and the issue persists, it seems that a mod changes the result of the anvil and by accident reverts the overenchantment
> > 
> > 
> > again, you have godsent patience to be able to do this and i cant thank you enough
> > as for the situation at hand i really dont know what to say, could it be a mod that tweaks the anvil yet it doesnt state that it does or it did state it and it went over my head somehow??
> 
> yeah it absolutely is. many mods might need to modify the anvil to have one feature working, one example of this is adventurez (but i already testet with and without it :d )

yeah advz is somehow not the culprit here in 1.20.1, in 1.19.2 it crashed with overenc and was clearly incompatible in every way but here its honestly worse since we have literally no clue which mod it is

**Comment by MastroCaleb** [comment]
> > > > > btw ive added a few new mods and removed a few others, all in all modpack hasnt changed much at all and this issue with the anvil is still ongoing sadly
> > > > > lmk if you want the "new" modpack
> > > > 
> > > > 
> > > > currently removing TONS of mods and the issue persists, it seems that a mod changes the result of the anvil and by accident reverts the overenchantment
> > > 
> > > 
> > > again, you have godsent patience to be able to do this and i cant thank you enough
> > > as for the situation at hand i really dont know what to say, could it be a mod that tweaks the anvil yet it doesnt state that it does or it did state it and it went over my head somehow??
> > 
> > 
> > yeah it absolutely is. many mods might need to modify the anvil to have one feature working, one example of this is adventurez (but i already testet with and without it :d )
> 
> yeah advz is somehow not the culprit here in 1.20.1, in 1.19.2 it crashed with overenc and was clearly incompatible in every way but here its honestly worse since we have literally no clue which mod it is

the funny thing is there is absolutely NO WAY that overenchanted is the problem, the code is WAY TOO SIMPLE right now.

before it was understandable, the code was incredibly instable and ran by hopes and dreams. 
the new code literally replaces "enchantment.getMaxLevel()" with "Integer.MAX_VALUE" so someone is absolutely modifying the anvil.

**Comment by MastroCaleb** [comment]
And the mod that causes troubles iiiiiisssssssssssssssssssssssssssssssssss:

Goblin Traders!

Yup, im gonna check exactly what they do in the anvil that makes my mod useless, if i find something i will tell ya

**Comment by MastroCaleb** [comment]
> And the mod that causes troubles iiiiiisssssssssssssssssssssssssssssssssss:
> 
> Goblin Traders!
> 
> Yup, im gonna check exactly what they do in the anvil that makes my mod useless, if i find something i will tell ya

Ok, this class right here is the problem:

https://github.com/MrCrayfish/GoblinTraders/blob/multiloader/1.20.X/common/src/main/java/com/mrcrayfish/goblintraders/mixin/RepairContainerMixin.java

I dont exaclty know how they would make it work, i dont have any experience with multiloader projects.
You should make a compatibility report on their github, link my mod's github repository and the class i sent you, they should be able to understand the issue.

**Comment by MastroCaleb** [comment]
> i dont ha

that's my best guess, if i remove it from the modpack the overenchanting works, if it's not the same on your pc im gonna jump off a balcony

**Comment by memphismc** [comment]
dude it WAS goblin traders... how the fuck though? i swear to god i didnt have the mod when i first encountered this issue
(funny ass coincidence too... we talked about goblin traders overenchanting lmao so ironic)

anyways... one issue solved, one issue still exists: relicex still duplicates (  ffs, why me? :(  )

https://github.com/MastroCaleb/OverEnchanted/assets/129392333/87c30c9d-4919-474b-8983-89e6079824e4

**Comment by MastroCaleb** [comment]
> dude it WAS goblin traders... how the fuck though? i swear to god i didnt have the mod when i first encountered this issue (funny ass coincidence too... we talked about goblin traders overenchanting lmao so ironic)
> 
> anyways... one issue solved, one issue still exists: relicex still duplicates ( ffs, why me? :( )
> 
>  Desktop.2024.03.13.-.21.22.17.01.mp4

is it my mod that makes it duplicate? that would be weird

**Comment by memphismc** [comment]
> > dude it WAS goblin traders... how the fuck though? i swear to god i didnt have the mod when i first encountered this issue (funny ass coincidence too... we talked about goblin traders overenchanting lmao so ironic)
> > anyways... one issue solved, one issue still exists: relicex still duplicates ( ffs, why me? :( )
> > Desktop.2024.03.13.-.21.22.17.01.mp4
> 
> is it my mod that makes it duplicate? that would be weird

no, still a pretty jarring issue though
remember those weird arrows that pop up on the anvil? yeah they still do, still havent found out what mod that is
this is the average modded minecraft experience right here, incompatibilities... always

**Comment by MastroCaleb** [comment]
> > > dude it WAS goblin traders... how the fuck though? i swear to god i didnt have the mod when i first encountered this issue (funny ass coincidence too... we talked about goblin traders overenchanting lmao so ironic)
> > > anyways... one issue solved, one issue still exists: relicex still duplicates ( ffs, why me? :( )
> > > Desktop.2024.03.13.-.21.22.17.01.mp4
> > 
> > 
> > is it my mod that makes it duplicate? that would be weird
> 
> no, still a pretty jarring issue though remember those weird arrows that pop up on the anvil? yeah they still do, still havent found out what mod that is this is the average modded minecraft experience right here, weird incompatibilities... always, something always has to be wrong

that's the problem with making your own modpacks ahah, do you know which mod adds that Relic?

**Comment by MastroCaleb** [comment]
> > > > > dude it WAS goblin traders... how the fuck though? i swear to god i didnt have the mod when i first encountered this issue (funny ass coincidence too... we talked about goblin traders overenchanting lmao so ironic)
> > > > > anyways... one issue solved, one issue still exists: relicex still duplicates ( ffs, why me? :( )
> > > > > Desktop.2024.03.13.-.21.22.17.01.mp4
> > > > 
> > > > 
> > > > is it my mod that makes it duplicate? that would be weird
> > > 
> > > 
> > > no, still a pretty jarring issue though remember those weird arrows that pop up on the anvil? yeah they still do, still havent found out what mod that is this is the average modded minecraft experience right here, weird incompatibilities... always, something always has to be wrong
> > 
> > 
> > that's the problem with making your own modpacks ahah, do you know which mod adds that Relic?
> 
> [RelicEX](https://www.curseforge.com/minecraft/mc-mods/relicex-directors-cut)

mh, thought i could find something in the source code but i didn't find anything. does this issue keep happening in survival or is it only creative?

**Comment by memphismc** [comment]
> > > > > > dude it WAS goblin traders... how the fuck though? i swear to god i didnt have the mod when i first encountered this issue (funny ass coincidence too... we talked about goblin traders overenchanting lmao so ironic)
> > > > > > anyways... one issue solved, one issue still exists: relicex still duplicates ( ffs, why me? :( )
> > > > > > Desktop.2024.03.13.-.21.22.17.01.mp4
> > > > > 
> > > > > 
> > > > > is it my mod that makes it duplicate? that would be weird
> > > > 
> > > > 
> > > > no, still a pretty jarring issue though remember those weird arrows that pop up on the anvil? yeah they still do, still havent found out what mod that is this is the average modded minecraft experience right here, weird incompatibilities... always, something always has to be wrong
> > > 
> > > 
> > > that's the problem with making your own modpacks ahah, do you know which mod adds that Relic?
> > 
> > 
> > [RelicEX](https://www.curseforge.com/minecraft/mc-mods/relicex-directors-cut)
> 
> mh, thought i could find something in the source code but i didn't find anything. does this issue keep happening in survival or is it only creative?

happens both in creative and survival, relicex devs said the mod on its own doesnt act like this so its once again some other culprit mod

**Comment by MastroCaleb** [comment]
> > > > > > > dude it WAS goblin traders... how the fuck though? i swear to god i didnt have the mod when i first encountered this issue (funny ass coincidence too... we talked about goblin traders overenchanting lmao so ironic)
> > > > > > > anyways... one issue solved, one issue still exists: relicex still duplicates ( ffs, why me? :( )
> > > > > > > Desktop.2024.03.13.-.21.22.17.01.mp4
> > > > > > 
> > > > > > 
> > > > > > is it my mod that makes it duplicate? that would be weird
> > > > > 
> > > > > 
> > > > > no, still a pretty jarring issue though remember those weird arrows that pop up on the anvil? yeah they still do, still havent found out what mod that is this is the average modded minecraft experience right here, weird incompatibilities... always, something always has to be wrong
> > > > 
> > > > 
> > > > that's the problem with making your own modpacks ahah, do you know which mod adds that Relic?
> > > 
> > > 
> > > [RelicEX](https://www.curseforge.com/minecraft/mc-mods/relicex-directors-cut)
> > 
> > 
> > mh, thought i could find something in the source code but i didn't find anything. does this issue keep happening in survival or is it only creative?
> 
> happens both in creative and survival, relicex devs said the mod on its own doesnt act like this so its once again some other culprit mod

the hate i feel for undiscolsed mixins inside random mods is bigger than ever rn. it probably has to do with an enchantment mod/anvil mod. try deleting every mod that adds enchantments and the bypass anvil restriction mod

**Comment by memphismc** [comment]
> > > > > > > > dude it WAS goblin traders... how the fuck though? i swear to god i didnt have the mod when i first encountered this issue (funny ass coincidence too... we talked about goblin traders overenchanting lmao so ironic)
> > > > > > > > anyways... one issue solved, one issue still exists: relicex still duplicates ( ffs, why me? :( )
> > > > > > > > Desktop.2024.03.13.-.21.22.17.01.mp4
> > > > > > > 
> > > > > > > 
> > > > > > > is it my mod that makes it duplicate? that would be weird
> > > > > > 
> > > > > > 
> > > > > > no, still a pretty jarring issue though remember those weird arrows that pop up on the anvil? yeah they still do, still havent found out what mod that is this is the average modded minecraft experience right here, weird incompatibilities... always, something always has to be wrong
> > > > > 
> > > > > 
> > > > > that's the problem with making your own modpacks ahah, do you know which mod adds that Relic?
> > > > 
> > > > 
> > > > [RelicEX](https://www.curseforge.com/minecraft/mc-mods/relicex-directors-cut)
> > > 
> > > 
> > > mh, thought i could find something in the source code but i didn't find anything. does this issue keep happening in survival or is it only creative?
> > 
> > 
> > happens both in creative and survival, relicex devs said the mod on its own doesnt act like this so its once again some other culprit mod
> 
> the hate i feel for undiscolsed mixins inside random mods is bigger than ever rn. it probably has to do with an enchantment mod/anvil mod. try deleting every mod that adds enchantments and the bypass anvil restriction mod

done this before, and also removed every other mod that adds anvils including adventurez and the issue still persists
oh tell me about it... i fucking hate this too

**Comment by MastroCaleb** [comment]
> > > > > > > > > dude it WAS goblin traders... how the fuck though? i swear to god i didnt have the mod when i first encountered this issue (funny ass coincidence too... we talked about goblin traders overenchanting lmao so ironic)
> > > > > > > > > anyways... one issue solved, one issue still exists: relicex still duplicates ( ffs, why me? :( )
> > > > > > > > > Desktop.2024.03.13.-.21.22.17.01.mp4
> > > > > > > > 
> > > > > > > > 
> > > > > > > > is it my mod that makes it duplicate? that would be weird
> > > > > > > 
> > > > > > > 
> > > > > > > no, still a pretty jarring issue though remember those weird arrows that pop up on the anvil? yeah they still do, still havent found out what mod that is this is the average modded minecraft experience right here, weird incompatibilities... always, something always has to be wrong
> > > > > > 
> > > > > > 
> > > > > > that's the problem with making your own modpacks ahah, do you know which mod adds that Relic?
> > > > > 
> > > > > 
> > > > > [RelicEX](https://www.curseforge.com/minecraft/mc-mods/relicex-directors-cut)
> > > > 
> > > > 
> > > > mh, thought i could find something in the source code but i didn't find anything. does this issue keep happening in survival or is it only creative?
> > > 
> > > 
> > > happens both in creative and survival, relicex devs said the mod on its own doesnt act like this so its once again some other culprit mod
> > 
> > 
> > the hate i feel for undiscolsed mixins inside random mods is bigger than ever rn. it probably has to do with an enchantment mod/anvil mod. try deleting every mod that adds enchantments and the bypass anvil restriction mod
> 
> done this before, and also removed every other mod that adds anvils including adventurez and the issue still persists oh tell me about it... i fucking hate this too

i have absolutely no idea then

**Comment by memphismc** [comment]
at long last ive found the culprit for relicex... its stackables

probably gonna quit modded minecraft for a good while now lol

**Comment by Koxae** [comment]
Hello. Sorry to intrude. But the conflict between goblin traders and over-enchantment continues in version 1.20.4

**Comment by MastroCaleb** [comment]
> Hello. Sorry to intrude. But the conflict between goblin traders and over-enchantment continues in version 1.20.4

Im extremely sorry but due to the "No Fabric API" nature of Over Enchanted i cannot fix this issue, it should be fixed by the Goblin Traders devs. I could help them make a fix but im currently not able to do so.

**Comment by Joshernoob** [comment]
Could this be changed to Goblin traders don't work with this mod? seems even in forge 1.20,1 they are a problem as well

also if thet could be added to the mods page as not compatable that be great, I was only lucky i check this instead of removing the mod as i head the Goblin traders already installed in a 400 mod modpack i have up on curse forge

**Comment by MastroCaleb** [comment]
> [Joshernoob](/Joshernoob)

True, i will add a text on the mod's page

**Comment by memphismc** [comment]
should i close this issue??? lol
ive stopped using this as ive sort of revamped my modpack to not include any OP shit

**Comment by Joshernoob** [comment]
For now @memphismc  I would change the name to something like bug: doesn't work with Goblin traders. 

Let the dev of this mod close it once the bugs fixed, as having it open make it easy to see there still a problem

**Comment by memphismc** [comment]
> For now @memphismc I would change the name to something like bug: doesn't work with Goblin traders.
> 
> Let the dev of this mod close it once the bugs fixed, as having it open make it easy to see there still a problem

sure, but ill let the dev decide on the title change
also, im not good in github but im sorta sure he can also change the title if he wants
